name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPOSITORY_ID: mkp-transactions-ms
  IMAGE_NAME: mkp-transactions-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WI_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Artifact Registry
      run: |
        gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_ID}/${IMAGE_NAME}:${GITHUB_SHA::7}
          ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_ID}/${IMAGE_NAME}:latest

    - name: Trigger Terraform Deployment
      uses: actions/github-script@v6
      env:
        IMAGE_TAG: ${{ github.sha }}
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'tu_org',
            repo: 'terraform-repo',
            workflow_id: 'deploy.yml',
            ref: 'main',
            inputs: {
              image_tag: process.env.IMAGE_TAG
            }
          })
