name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPOSITORY_ID: mkp-transactions-ms
  IMAGE_NAME: mkp-transactions-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WI_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        token_format: 'access_token'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Docker login to Artifact Registry
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{secrets.REGION}}-docker.pkg.dev

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{secrets.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{secrets.REPOSITORY_ID}}/${{secrets.IMAGE_NAME}}:${{github.sha}}
          ${{secrets.REGION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{secrets.REPOSITORY_ID}}/${{secrets.IMAGE_NAME}}:latest

    - name: Trigger Terraform Deployment
      uses: actions/github-script@v6
      env:
        IMAGE_TAG: ${{ github.sha }}
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'tu_org',
            repo: 'terraform-repo',
            workflow_id: 'deploy.yml',
            ref: 'main',
            inputs: {
              image_tag: process.env.IMAGE_TAG
            }
          })
